#ifndef USER_CONFIG_H
#define USER_CONFIG_H

// wifi config
#define WIFI_SSID "PhoneBed"
#define WIFI_PASSWORD "12345678"

// spi handle
#define SDSPI_HOST SPI2_HOST
#define LCD_HOST SPI3_HOST

// ESP32 I2C
#define ESP32_SCL_NUM (GPIO_NUM_48)
#define ESP32_SDA_NUM (GPIO_NUM_47)

// Touch I2C
#define Touch_SCL_NUM (GPIO_NUM_18)
#define Touch_SDA_NUM (GPIO_NUM_17)

// PCF85063
#define RTC_PCF85063_ADDR 0x51

// qmi8658
#define IMU_QMI8658_ADDR 0x6B

//  DISP
#define EXAMPLE_LCD_H_RES 172
#define EXAMPLE_LCD_V_RES 640
#define LVGL_DMA_BUFF_LEN (EXAMPLE_LCD_H_RES * 64 * 2)
#define LVGL_SPIRAM_BUFF_LEN (EXAMPLE_LCD_H_RES * EXAMPLE_LCD_V_RES * 2)

#define USER_DISP_ROT_90 1
#define USER_DISP_ROT_NONO 0
#define Rotated USER_DISP_ROT_90 // 软件实现旋转

// LCD PIN
#define EXAMPLE_PIN_NUM_LCD_CS (GPIO_NUM_9)
#define EXAMPLE_PIN_NUM_LCD_PCLK (GPIO_NUM_10)
#define EXAMPLE_PIN_NUM_LCD_DATA0 (GPIO_NUM_11)
#define EXAMPLE_PIN_NUM_LCD_DATA1 (GPIO_NUM_12)
#define EXAMPLE_PIN_NUM_LCD_DATA2 (GPIO_NUM_13)
#define EXAMPLE_PIN_NUM_LCD_DATA3 (GPIO_NUM_14)
#define EXAMPLE_PIN_NUM_LCD_RST (GPIO_NUM_21)
#define EXAMPLE_PIN_NUM_BK_LIGHT (GPIO_NUM_8)

#define DISP_TOUCH_ADDR 0x3B
#define EXAMPLE_PIN_NUM_TOUCH_RST (-1)
#define EXAMPLE_PIN_NUM_TOUCH_INT (-1)

// MOTOR
// v1.0
#define MOTOR_PWM_PIN1 (GPIO_NUM_2)
#define MOTOR_PWM_PIN2 (GPIO_NUM_3)
// v1.1
// #define MOTOR_PWM_PIN1 (GPIO_NUM_3)
// #define MOTOR_PWM_PIN2 (GPIO_NUM_2)
#define MOTOR_PWM_PIN3 (GPIO_NUM_4)
#define MOTOR_PWM_PIN4 (GPIO_NUM_5)

// MOTOR_LIMIT
#define MOTOR_LIMIT_HEAD_PIN (GPIO_NUM_40)
#define MOTOR_LIMIT_BOTTOM_PIN (GPIO_NUM_38)

// FAN
#define FAN_PWM_PIN (GPIO_NUM_1)

// BUTTON
#define BUTTON_PIN1 (GPIO_NUM_41)
#define BUTTON_PIN2 (GPIO_NUM_43)

// CHARGE
#define CHARGE_PIN (GPIO_NUM_44)

#endif